version: 2

models:
  - name: pitches
    description: "A starter dbt model"
    columns:
      - Pitch: Pitch
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - Type: Type
